import { MongoClient, Db } from "mongodb";

var uri = "mongodb://lorenzo:PWD@unibo-orientation-cluster-shard-00-00-p2i0j.mongodb.net:27017,unibo-orientation-cluster-shard-00-01-p2i0j.mongodb.net:27017,unibo-orientation-cluster-shard-00-02-p2i0j.mongodb.net:27017/unibo-orientation?ssl=true&replicaSet=unibo-orientation-cluster-shard-0&authSource=admin";

var inserted = 0;

MongoClient.connect(uri, function (err, db: Db) {
    if (err) {
        console.log(err);
        process.exit(1);
    }
    var answers = [{
        groupName: "Agrario", courseCodes: ["8526", "8883", "8532", "8525", "9235", "8531", "8527", "8523", "8524", "8528"], answers:
        {
            "Ti piace stare a contatto con la natura?": 1,
            "Sei cosciente dell'ambiente?": 1,
            "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 1,
            "Ti piacerebbe vivere in campagna?": 1,
            "Ti piace stare a contatto con gli animali?": 0.5,
            "Ti piace lavorare con i numeri?": 0,
            "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.5,
            "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0.5,
            "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0.5,
            "Ti piace la pubblicità?": 0,
            "Lavoreresti nei weekend per ottenere successo?": 0,
            "Vorresti lavorare nel mondo dello sport?": 0.5,
            "Ti piacerebbe lavorare aiutando gli altri?": 0.5,
            "Ti piace lavorare con i computer?": 0,
            "Ti piace capire come funzionano le cose e crearne nuove?": 0,
            "Sei interessato alle ultime novità tecnologiche?": 0,
            "Pensi sia importante seguire leggi e regole?": 0.5,
            "Ti piace leggere?": 0,
            "Ti piace andare in musei o al teatro?": 0,
            "Lo stipendio è importante per te?": 0,
            "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
            "Trovi divertente imparare nuove lingue?": 0,
            "Sei bravo ad insegnare agli altri?": 0.5,
            "Ti piace stare a contatto con i bambini?": 0,
            "Ti piace leggere statistiche?": 0.5,
            "Vorresti lavorare in un ambiente internazionale?": 0.33,
            "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
            "Pensi e rifletti prima di agire?": 0.5,
            "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
            "Il fitness e la salute sono importanti per te?": 0.5,
            "Ti piace dare consigli?": 0.5,
            "Vorresti capire il funzionamento del corpo umano?": 0
        }
    }, {
            groupName: "Veterinario", courseCodes: ["8834", "8522", "8617", "8882", "8521"], answers:
            {
                "Ti piace stare a contatto con la natura?": 1,
                "Sei cosciente dell'ambiente?": 1,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 1,
                "Ti piacerebbe vivere in campagna?": 1,
                "Ti piace stare a contatto con gli animali?": 1,
                "Ti piace lavorare con i numeri?": 0,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0.5,
                "Ti piace la pubblicità?": 0.5,
                "Lavoreresti nei weekend per ottenere successo?": 0.5,
                "Vorresti lavorare nel mondo dello sport?": 0.5,
                "Ti piacerebbe lavorare aiutando gli altri?": 1,
                "Ti piace lavorare con i computer?": 0,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                "Sei interessato alle ultime novità tecnologiche?": 0,
                "Pensi sia importante seguire leggi e regole?": 0.5,
                "Ti piace leggere?": 0,
                "Ti piace andare in musei o al teatro?": 0,
                "Lo stipendio è importante per te?": 0,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                "Trovi divertente imparare nuove lingue?": 0,
                "Sei bravo ad insegnare agli altri?": 0.5,
                "Ti piace stare a contatto con i bambini?": 0,
                "Ti piace leggere statistiche?": 0,
                "Vorresti lavorare in un ambiente internazionale?": 0,
                "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                "Pensi e rifletti prima di agire?": 0.5,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                "Il fitness e la salute sono importanti per te?": 1,
                "Ti piace dare consigli?": 0.5,
                "Vorresti capire il funzionamento del corpo umano?": 0.75
            }
    }, {
            groupName: "Economico", courseCodes: ["8871", "0897", "8965", "9221", "8408", "0902", "8873", "9202", "8038", "8880",
                "8839", "8609", "0905", "0900", "0901", "8854", "8842", "8848", "8420", "8872", "8406", "8876", "8847", "9203",
                "8835", "8843", "8877"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0,
                    "Sei cosciente dell'ambiente?": 0,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                    "Ti piacerebbe vivere in campagna?": 0,
                    "Ti piace stare a contatto con gli animali?": 0,
                    "Ti piace lavorare con i numeri?": 1,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 1,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 1,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                    "Ti piace la pubblicità?": 1,
                    "Lavoreresti nei weekend per ottenere successo?": 1,
                    "Vorresti lavorare nel mondo dello sport?": 0,
                    "Ti piacerebbe lavorare aiutando gli altri?": 0,
                    "Ti piace lavorare con i computer?": 0.75,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                    "Sei interessato alle ultime novità tecnologiche?": 0.5,
                    "Pensi sia importante seguire leggi e regole?": 1,
                    "Ti piace leggere?": 0,
                    "Ti piace andare in musei o al teatro?": 0,
                    "Lo stipendio è importante per te?": 1,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                    "Trovi divertente imparare nuove lingue?": 0,
                    "Sei bravo ad insegnare agli altri?": 0.5,
                    "Ti piace stare a contatto con i bambini?": 0,
                    "Ti piace leggere statistiche?": 1,
                    "Vorresti lavorare in un ambiente internazionale?": 1,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                    "Pensi e rifletti prima di agire?": 1,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 1,
                    "Il fitness e la salute sono importanti per te?": 0,
                    "Ti piace dare consigli?": 0.5,
                    "Vorresti capire il funzionamento del corpo umano?": 0
                }
    }, {
            groupName: "Farmacetico", courseCodes: ["9212", "8519", "8412", "9213", "8518", "9211", "8021", "8005", "9223", "9219"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0,
                "Sei cosciente dell'ambiente?": 0,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0,
                "Ti piace stare a contatto con gli animali?": 0,
                "Ti piace lavorare con i numeri?": 0.25,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.33,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0.5,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                "Ti piace la pubblicità?": 1,
                "Lavoreresti nei weekend per ottenere successo?": 0,
                "Vorresti lavorare nel mondo dello sport?": 0.5,
                "Ti piacerebbe lavorare aiutando gli altri?": 1,
                "Ti piace lavorare con i computer?": 0,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                "Sei interessato alle ultime novità tecnologiche?": 0,
                "Pensi sia importante seguire leggi e regole?": 1,
                "Ti piace leggere?": 0,
                "Ti piace andare in musei o al teatro?": 0,
                "Lo stipendio è importante per te?": 1,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                "Trovi divertente imparare nuove lingue?": 0,
                "Sei bravo ad insegnare agli altri?": 0.5,
                "Ti piace stare a contatto con i bambini?": 0,
                "Ti piace leggere statistiche?": 0,
                "Vorresti lavorare in un ambiente internazionale?": 0,
                "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                "Pensi e rifletti prima di agire?": 0.5,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0,
                "Il fitness e la salute sono importanti per te?": 1,
                "Ti piace dare consigli?": 1,
                "Vorresti capire il funzionamento del corpo umano?": 1
            }
    }, {
            groupName: "Motorio", courseCodes: ["8512", "9227", "9214", "8037", "9215", "8766"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0.5,
                "Sei cosciente dell'ambiente?": 0.5,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0.5,
                "Ti piace stare a contatto con gli animali?": 0,
                "Ti piace lavorare con i numeri?": 0,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.75,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0.5,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                "Ti piace la pubblicità?": 0.5,
                "Lavoreresti nei weekend per ottenere successo?": 1,
                "Vorresti lavorare nel mondo dello sport?": 1,
                "Ti piacerebbe lavorare aiutando gli altri?": 0.75,
                "Ti piace lavorare con i computer?": 0,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                "Sei interessato alle ultime novità tecnologiche?": 0,
                "Pensi sia importante seguire leggi e regole?": 0,
                "Ti piace leggere?": 0,
                "Ti piace andare in musei o al teatro?": 0,
                "Lo stipendio è importante per te?": 0,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                "Trovi divertente imparare nuove lingue?": 0,
                "Sei bravo ad insegnare agli altri?": 1,
                "Ti piace stare a contatto con i bambini?": 1,
                "Ti piace leggere statistiche?": 0.5,
                "Vorresti lavorare in un ambiente internazionale?": 0.5,
                "Ti piace imparare nuove cose, anche senza una guida?": 0,
                "Pensi e rifletti prima di agire?": 0,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 1,
                "Il fitness e la salute sono importanti per te?": 1,
                "Ti piace dare consigli?": 1,
                "Vorresti capire il funzionamento del corpo umano?": 1
            }
    }, {
            groupName: "Ingegneristico", courseCodes: ["9238", "0881", "0946", "8888", "8770", "0936", "0949", "8769", "9234",
                "0930", "9217", "0923", "0925", "0938", "9205", "9021", "8182", "8611", "9239", "8895", "8610", "0940", "0924", "0934",
                "0935", "0927", "9198", "8891", "8198", "8829", "9199", "8767", "8771", "8894"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0,
                    "Sei cosciente dell'ambiente?": 0.33,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                    "Ti piacerebbe vivere in campagna?": 0,
                    "Ti piace stare a contatto con gli animali?": 0,
                    "Ti piace lavorare con i numeri?": 1,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.75,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0.5,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0,
                    "Ti piace la pubblicità?": 0,
                    "Lavoreresti nei weekend per ottenere successo?": 1,
                    "Vorresti lavorare nel mondo dello sport?": 0,
                    "Ti piacerebbe lavorare aiutando gli altri?": 0.25,
                    "Ti piace lavorare con i computer?": 0.75,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 1,
                    "Sei interessato alle ultime novità tecnologiche?": 0.75,
                    "Pensi sia importante seguire leggi e regole?": 0.5,
                    "Ti piace leggere?": 0,
                    "Ti piace andare in musei o al teatro?": 0,
                    "Lo stipendio è importante per te?": 1,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                    "Trovi divertente imparare nuove lingue?": 0,
                    "Sei bravo ad insegnare agli altri?": 0,
                    "Ti piace stare a contatto con i bambini?": 0,
                    "Ti piace leggere statistiche?": 0.75,
                    "Vorresti lavorare in un ambiente internazionale?": 0.5,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                    "Pensi e rifletti prima di agire?": 1,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                    "Il fitness e la salute sono importanti per te?": 0,
                    "Ti piace dare consigli?": 0,
                    "Vorresti capire il funzionamento del corpo umano?": 0
                }
    }, {
            groupName: "Informatico", courseCodes: ["8614", "0926", "0937", "8014", "8028", "8009", "8615"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0,
                "Sei cosciente dell'ambiente?": 0,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0,
                "Ti piace stare a contatto con gli animali?": 0,
                "Ti piace lavorare con i numeri?": 1,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 1,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0,
                "Ti piace la pubblicità?": 0,
                "Lavoreresti nei weekend per ottenere successo?": 1,
                "Vorresti lavorare nel mondo dello sport?": 0,
                "Ti piacerebbe lavorare aiutando gli altri?": 0,
                "Ti piace lavorare con i computer?": 1,
                "Ti piace capire come funzionano le cose e crearne nuove?": 1,
                "Sei interessato alle ultime novità tecnologiche?": 1,
                "Pensi sia importante seguire leggi e regole?": 0.5,
                "Ti piace leggere?": 0,
                "Ti piace andare in musei o al teatro?": 0,
                "Lo stipendio è importante per te?": 1,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                "Trovi divertente imparare nuove lingue?": 0,
                "Sei bravo ad insegnare agli altri?": 0,
                "Ti piace stare a contatto con i bambini?": 0,
                "Ti piace leggere statistiche?": 0.5,
                "Vorresti lavorare in un ambiente internazionale?": 0.5,
                "Ti piace imparare nuove cose, anche senza una guida?": 1,
                "Pensi e rifletti prima di agire?": 1,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                "Il fitness e la salute sono importanti per te?": 0,
                "Ti piace dare consigli?": 0,
                "Vorresti capire il funzionamento del corpo umano?": 0
            }
    }, {
            groupName: "Fisico", courseCodes: ["8018", "8027", "8418", "8626", "8011", "8419", "8025", "8016", "8209", "8004",
                "8007", "8015"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0.5,
                    "Sei cosciente dell'ambiente?": 1,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 1,
                    "Ti piacerebbe vivere in campagna?": 0.5,
                    "Ti piace stare a contatto con gli animali?": 0.5,
                    "Ti piace lavorare con i numeri?": 1,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 0,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                    "Ti piace la pubblicità?": 0,
                    "Lavoreresti nei weekend per ottenere successo?": 0.5,
                    "Vorresti lavorare nel mondo dello sport?": 0.5,
                    "Ti piacerebbe lavorare aiutando gli altri?": 0.25,
                    "Ti piace lavorare con i computer?": 0.5,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 1,
                    "Sei interessato alle ultime novità tecnologiche?": 0.5,
                    "Pensi sia importante seguire leggi e regole?": 0.5,
                    "Ti piace leggere?": 0,
                    "Ti piace andare in musei o al teatro?": 0,
                    "Lo stipendio è importante per te?": 0.5,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                    "Trovi divertente imparare nuove lingue?": 0,
                    "Sei bravo ad insegnare agli altri?": 0.5,
                    "Ti piace stare a contatto con i bambini?": 0,
                    "Ti piace leggere statistiche?": 0.5,
                    "Vorresti lavorare in un ambiente internazionale?": 0.5,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                    "Pensi e rifletti prima di agire?": 1,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0,
                    "Il fitness e la salute sono importanti per te?": 0.5,
                    "Ti piace dare consigli?": 0,
                    "Vorresti capire il funzionamento del corpo umano?": 0
                }
    }, {
            groupName: "Chimico", courseCodes: ["8896", "8887", "8856", "8513", "8857", "0884", "8026", "8020", "8515",
                "8514", "8537", "8006", "8012"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 1,
                    "Sei cosciente dell'ambiente?": 1,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 1,
                    "Ti piacerebbe vivere in campagna?": 0.5,
                    "Ti piace stare a contatto con gli animali?": 0.5,
                    "Ti piace lavorare con i numeri?": 0.5,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 0,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0.5,
                    "Ti piace la pubblicità?": 0,
                    "Lavoreresti nei weekend per ottenere successo?": 0.5,
                    "Vorresti lavorare nel mondo dello sport?": 0,
                    "Ti piacerebbe lavorare aiutando gli altri?": 0.75,
                    "Ti piace lavorare con i computer?": 0.5,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 1,
                    "Sei interessato alle ultime novità tecnologiche?": 0.5,
                    "Pensi sia importante seguire leggi e regole?": 0,
                    "Ti piace leggere?": 0,
                    "Ti piace andare in musei o al teatro?": 0,
                    "Lo stipendio è importante per te?": 0.5,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                    "Trovi divertente imparare nuove lingue?": 0,
                    "Sei bravo ad insegnare agli altri?": 0.5,
                    "Ti piace stare a contatto con i bambini?": 0,
                    "Ti piace leggere statistiche?": 0,
                    "Vorresti lavorare in un ambiente internazionale?": 0,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                    "Pensi e rifletti prima di agire?": 0.5,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 1,
                    "Il fitness e la salute sono importanti per te?": 0.5,
                    "Ti piace dare consigli?": 0,
                    "Vorresti capire il funzionamento del corpo umano?": 1
                }
    }, {
            groupName: "Matematico", courseCodes: ["9222", "8010", "8208"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0.5,
                "Sei cosciente dell'ambiente?": 0.5,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0.5,
                "Ti piace stare a contatto con gli animali?": 0,
                "Ti piace lavorare con i numeri?": 1,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0,
                "Ti piace la pubblicità?": 0,
                "Lavoreresti nei weekend per ottenere successo?": 1,
                "Vorresti lavorare nel mondo dello sport?": 0,
                "Ti piacerebbe lavorare aiutando gli altri?": 0,
                "Ti piace lavorare con i computer?": 1,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0.75,
                "Sei interessato alle ultime novità tecnologiche?": 0.5,
                "Pensi sia importante seguire leggi e regole?": 0.5,
                "Ti piace leggere?": 0,
                "Ti piace andare in musei o al teatro?": 0,
                "Lo stipendio è importante per te?": 1,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                "Trovi divertente imparare nuove lingue?": 0,
                "Sei bravo ad insegnare agli altri?": 0.5,
                "Ti piace stare a contatto con i bambini?": 0,
                "Ti piace leggere statistiche?": 1,
                "Vorresti lavorare in un ambiente internazionale?": 0,
                "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                "Pensi e rifletti prima di agire?": 1,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0,
                "Il fitness e la salute sono importanti per te?": 0,
                "Ti piace dare consigli?": 0,
                "Vorresti capire il funzionamento del corpo umano?": 0
            }
    }, {
            groupName: "Giuridico", courseCodes: ["9231", "9233", "9232", "9230"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0,
                "Sei cosciente dell'ambiente?": 0.5,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0.5,
                "Ti piace stare a contatto con gli animali?": 0.5,
                "Ti piace lavorare con i numeri?": 0,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.5,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0.5,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                "Ti piace la pubblicità?": 0.5,
                "Lavoreresti nei weekend per ottenere successo?": 0.5,
                "Vorresti lavorare nel mondo dello sport?": 0,
                "Ti piacerebbe lavorare aiutando gli altri?": 1,
                "Ti piace lavorare con i computer?": 0,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                "Sei interessato alle ultime novità tecnologiche?": 0,
                "Pensi sia importante seguire leggi e regole?": 1,
                "Ti piace leggere?": 1,
                "Ti piace andare in musei o al teatro?": 1,
                "Lo stipendio è importante per te?": 0,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0.25,
                "Trovi divertente imparare nuove lingue?": 0,
                "Sei bravo ad insegnare agli altri?": 0.5,
                "Ti piace stare a contatto con i bambini?": 0,
                "Ti piace leggere statistiche?": 0,
                "Vorresti lavorare in un ambiente internazionale?": 0.5,
                "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                "Pensi e rifletti prima di agire?": 1,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                "Il fitness e la salute sono importanti per te?": 0,
                "Ti piace dare consigli?": 0,
                "Vorresti capire il funzionamento del corpo umano?": 0
            }
    }, {
            groupName: "Letterato", courseCodes: ["8885", "9220", "0970", "8838", "8850", "0983"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0,
                "Sei cosciente dell'ambiente?": 0.5,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0.5,
                "Ti piace stare a contatto con gli animali?": 0.5,
                "Ti piace lavorare con i numeri?": 0,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 0.5,
                "Ti piace la pubblicità?": 0.5,
                "Lavoreresti nei weekend per ottenere successo?": 0,
                "Vorresti lavorare nel mondo dello sport?": 0,
                "Ti piacerebbe lavorare aiutando gli altri?": 0,
                "Ti piace lavorare con i computer?": 0,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                "Sei interessato alle ultime novità tecnologiche?": 0,
                "Pensi sia importante seguire leggi e regole?": 0.5,
                "Ti piace leggere?": 1,
                "Ti piace andare in musei o al teatro?": 1,
                "Lo stipendio è importante per te?": 0,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 1,
                "Trovi divertente imparare nuove lingue?": 0.5,
                "Sei bravo ad insegnare agli altri?": 1,
                "Ti piace stare a contatto con i bambini?": 0.5,
                "Ti piace leggere statistiche?": 0,
                "Vorresti lavorare in un ambiente internazionale?": 0,
                "Ti piace imparare nuove cose, anche senza una guida?": 0,
                "Pensi e rifletti prima di agire?": 0.5,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                "Il fitness e la salute sono importanti per te?": 0,
                "Ti piace dare consigli?": 0.5,
                "Vorresti capire il funzionamento del corpo umano?": 0
            }
    }, {
            groupName: "Culturale", courseCodes: ["0964", "8849", "9224", "0971", "8773", "9218", "0956", "9216", "8493", "0966", "8837",
                "8845", "0977", "8772", "0962", "8855", "8616", "9022", "8886"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0.5,
                    "Sei cosciente dell'ambiente?": 0.5,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 1,
                    "Ti piacerebbe vivere in campagna?": 0.5,
                    "Ti piace stare a contatto con gli animali?": 0.5,
                    "Ti piace lavorare con i numeri?": 0,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 0,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                    "Ti piace la pubblicità?": 1,
                    "Lavoreresti nei weekend per ottenere successo?": 0,
                    "Vorresti lavorare nel mondo dello sport?": 0,
                    "Ti piacerebbe lavorare aiutando gli altri?": 0,
                    "Ti piace lavorare con i computer?": 0,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                    "Sei interessato alle ultime novità tecnologiche?": 0,
                    "Pensi sia importante seguire leggi e regole?": 0.5,
                    "Ti piace leggere?": 1,
                    "Ti piace andare in musei o al teatro?": 1,
                    "Lo stipendio è importante per te?": 0,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 1,
                    "Trovi divertente imparare nuove lingue?": 1,
                    "Sei bravo ad insegnare agli altri?": 0.5,
                    "Ti piace stare a contatto con i bambini?": 0.5,
                    "Ti piace leggere statistiche?": 0,
                    "Vorresti lavorare in un ambiente internazionale?": 1,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0,
                    "Pensi e rifletti prima di agire?": 0,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                    "Il fitness e la salute sono importanti per te?": 0,
                    "Ti piace dare consigli?": 0.5,
                    "Vorresti capire il funzionamento del corpo umano?": 0
                }
    }, {
            groupName: "Linguistico", courseCodes: ["8874", "8059", "8060", "0980", "0981", "0979", "9174"], answers:
            {
                "Ti piace stare a contatto con la natura?": 0,
                "Sei cosciente dell'ambiente?": 0.5,
                "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                "Ti piacerebbe vivere in campagna?": 0,
                "Ti piace stare a contatto con gli animali?": 0,
                "Ti piace lavorare con i numeri?": 0,
                "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.5,
                "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 1,
                "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                "Ti piace la pubblicità?": 1,
                "Lavoreresti nei weekend per ottenere successo?": 0,
                "Vorresti lavorare nel mondo dello sport?": 0,
                "Ti piacerebbe lavorare aiutando gli altri?": 0.5,
                "Ti piace lavorare con i computer?": 0,
                "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                "Sei interessato alle ultime novità tecnologiche?": 0,
                "Pensi sia importante seguire leggi e regole?": 0.5,
                "Ti piace leggere?": 1,
                "Ti piace andare in musei o al teatro?": 0.5,
                "Lo stipendio è importante per te?": 0,
                "Ti piace la storia, la religione e questioni che riguardano la società?": 0.5,
                "Trovi divertente imparare nuove lingue?": 1,
                "Sei bravo ad insegnare agli altri?": 1,
                "Ti piace stare a contatto con i bambini?": 0.5,
                "Ti piace leggere statistiche?": 0,
                "Vorresti lavorare in un ambiente internazionale?": 1,
                "Ti piace imparare nuove cose, anche senza una guida?": 1,
                "Pensi e rifletti prima di agire?": 0,
                "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                "Il fitness e la salute sono importanti per te?": 0,
                "Ti piace dare consigli?": 0.5,
                "Vorresti capire il funzionamento del corpo umano?": 0
            }
    }, {
            groupName: "Politico", courseCodes: ["8840", "8782", "8040", "8784", "8853", "9200", "9237", "8048", "8786",
                "8051", "8783", "8890", "8049", "8491", "8495"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0,
                    "Sei cosciente dell'ambiente?": 1,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 1,
                    "Ti piacerebbe vivere in campagna?": 0.5,
                    "Ti piace stare a contatto con gli animali?": 0,
                    "Ti piace lavorare con i numeri?": 0.5,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 1,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 1,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                    "Ti piace la pubblicità?": 1,
                    "Lavoreresti nei weekend per ottenere successo?": 0,
                    "Vorresti lavorare nel mondo dello sport?": 0,
                    "Ti piacerebbe lavorare aiutando gli altri?": 1,
                    "Ti piace lavorare con i computer?": 0,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                    "Sei interessato alle ultime novità tecnologiche?": 0,
                    "Pensi sia importante seguire leggi e regole?": 1,
                    "Ti piace leggere?": 1,
                    "Ti piace andare in musei o al teatro?": 1,
                    "Lo stipendio è importante per te?": 0,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 1,
                    "Trovi divertente imparare nuove lingue?": 0.5,
                    "Sei bravo ad insegnare agli altri?": 1,
                    "Ti piace stare a contatto con i bambini?": 0,
                    "Ti piace leggere statistiche?": 0,
                    "Vorresti lavorare in un ambiente internazionale?": 1,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0.5,
                    "Pensi e rifletti prima di agire?": 0.5,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 1,
                    "Il fitness e la salute sono importanti per te?": 0,
                    "Ti piace dare consigli?": 1,
                    "Vorresti capire il funzionamento del corpo umano?": 0
                }
    }, {
            groupName: "Psicologico", courseCodes: ["8775", "9206", "0993", "9228", "8540", "0989", "0991",
                "9236", "8777", "0990", "8774", "8776", "9229", "8780"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0.5,
                    "Sei cosciente dell'ambiente?": 0.5,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                    "Ti piacerebbe vivere in campagna?": 0.5,
                    "Ti piace stare a contatto con gli animali?": 0.5,
                    "Ti piace lavorare con i numeri?": 0,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 0.5,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 1,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                    "Ti piace la pubblicità?": 0.5,
                    "Lavoreresti nei weekend per ottenere successo?": 0,
                    "Vorresti lavorare nel mondo dello sport?": 0,
                    "Ti piacerebbe lavorare aiutando gli altri?": 1,
                    "Ti piace lavorare con i computer?": 0,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                    "Sei interessato alle ultime novità tecnologiche?": 0,
                    "Pensi sia importante seguire leggi e regole?": 0.5,
                    "Ti piace leggere?": 0.5,
                    "Ti piace andare in musei o al teatro?": 0.5,
                    "Lo stipendio è importante per te?": 0,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 0.5,
                    "Trovi divertente imparare nuove lingue?": 0,
                    "Sei bravo ad insegnare agli altri?": 1,
                    "Ti piace stare a contatto con i bambini?": 1,
                    "Ti piace leggere statistiche?": 0.5,
                    "Vorresti lavorare in un ambiente internazionale?": 0,
                    "Ti piace imparare nuove cose, anche senza una guida?": 0,
                    "Pensi e rifletti prima di agire?": 0,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 1,
                    "Il fitness e la salute sono importanti per te?": 0.5,
                    "Ti piace dare consigli?": 1,
                    "Vorresti capire il funzionamento del corpo umano?": 0.75
                }
    }, {
            groupName: "Medico", courseCodes: ["8477", "8475", "9201", "8484", "8470", "8474", "8204", "8487", "8483", "8859",
                "8473", "9210", "8488", "8486", "8476", "8879", "8481", "8415", "8878", "8485", "8478", "8479", "8482"], answers:
                {
                    "Ti piace stare a contatto con la natura?": 0,
                    "Sei cosciente dell'ambiente?": 0.5,
                    "Sei interessato ai fenomeni naturali e al riscaldamento globale?": 0.5,
                    "Ti piacerebbe vivere in campagna?": 0.5,
                    "Ti piace stare a contatto con gli animali?": 0.5,
                    "Ti piace lavorare con i numeri?": 0,
                    "Ti piace pianificare, organizzare e strutturare il lavoro?": 1,
                    "Ti piacerebbe lavorare a stretto contatto con il personale aziendale?": 0,
                    "Preferisci stare a contatto con le persone piuttosto che stare da solo?": 1,
                    "Ti piace la pubblicità?": 0,
                    "Lavoreresti nei weekend per ottenere successo?": 1,
                    "Vorresti lavorare nel mondo dello sport?": 0.5,
                    "Ti piacerebbe lavorare aiutando gli altri?": 1,
                    "Ti piace lavorare con i computer?": 0,
                    "Ti piace capire come funzionano le cose e crearne nuove?": 0,
                    "Sei interessato alle ultime novità tecnologiche?": 0.5,
                    "Pensi sia importante seguire leggi e regole?": 0.5,
                    "Ti piace leggere?": 0.5,
                    "Ti piace andare in musei o al teatro?": 0,
                    "Lo stipendio è importante per te?": 1,
                    "Ti piace la storia, la religione e questioni che riguardano la società?": 0,
                    "Trovi divertente imparare nuove lingue?": 0,
                    "Sei bravo ad insegnare agli altri?": 1,
                    "Ti piace stare a contatto con i bambini?": 1,
                    "Ti piace leggere statistiche?": 1,
                    "Vorresti lavorare in un ambiente internazionale?": 0,
                    "Ti piace imparare nuove cose, anche senza una guida?": 1,
                    "Pensi e rifletti prima di agire?": 1,
                    "Saresti a tuo agio lavorando con informazioni incomplete o ambigue?": 0.5,
                    "Il fitness e la salute sono importanti per te?": 1,
                    "Ti piace dare consigli?": 1,
                    "Vorresti capire il funzionamento del corpo umano?": 1
                }
    }];
    for (let i = 0; i < answers.length;i++) {
        let answer = answers[i];
        db.collection('answers').insert(answer), (err, res) => {
            if (err) {
                console.log(err);
                process.exit(1);
            }
            inserted++;
            console.log(inserted);
            if (inserted === answers.length)
                process.exit(0);
        }
    }
});
